/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const $QueryResponse = {
    properties: {
        response: {
            type: 'string',
            description: `Response generated by the chatbot`,
            isRequired: true,
        },
    },
} as const;
