/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type QueryResponse = {
    /**
     * Response generated by the chatbot
     */
    response: string;
};

