"""Add category to recipes

Revision ID: 0f3c3f116823
Revises: 86714936f063
Create Date: 2024-07-04 23:40:46.795325

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0f3c3f116823'
down_revision = '86714936f063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'category')
    # ### end Alembic commands ###
