"""Updated user relationship

Revision ID: 6d1b1ae0a011
Revises: ce05dfc64722
Create Date: 2024-06-20 23:51:41.207907

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6d1b1ae0a011'
down_revision = 'ce05dfc64722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
