"""Added comments and extended recipes

Revision ID: ce05dfc64722
Revises: a0cfbe3a5ae6
Create Date: 2024-06-20 23:26:40.610765

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ce05dfc64722'
down_revision = 'a0cfbe3a5ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('recipe', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('recipe', sa.Column('store_in_vector_db', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'store_in_vector_db')
    op.drop_column('recipe', 'description')
    op.drop_table('comment')
    # ### end Alembic commands ###
