"""Updated models to use camelCase

Revision ID: dc7f31f1b429
Revises: 6d1b1ae0a011
Create Date: 2024-06-22 23:59:22.843775

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dc7f31f1b429'
down_revision = '6d1b1ae0a011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
