name: Run ESLint and Type Checker

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version-file: "frontend/.nvmrc"

      - name: Install node dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run type checker
        working-directory: ./frontend
        run: npm run tsc

      - name: Run linter
        working-directory: ./frontend
        run: npm run lint
